Dz6
dmitryf8/FedorovichAndroidPvt pull request #4
Opened 2019-06-29 19:10 UTC by dmitryf8

2019-06-30 16:58 UTC, tim-teacher requested changes

2019-06-30 16:58 UTC, jushlwest commented on app/src/main/java/by/itacademy/pvt/homework/ImageLoader.kt
> +class ImageLoader {
не вижу смысла в классе тут, вам приходится каждый раз создавать его объект, удалите класс и оставьте просто методы в файле

2019-06-30 16:58 UTC, jushlwest commented on app/src/main/java/by/itacademy/pvt/homework/dz5/CustomDiagramView.kt
> +class CustomDiagramView : View {
а диаграмма каким боком тут?

2019-06-30 16:58 UTC, jushlwest commented on app/src/main/java/by/itacademy/pvt/homework/dz6/DZ6ListViewHolder.kt
> +        var imageLoader = ImageLoader()
создаете объект каждый раз когда проиходит заполнение полей, думаю можно вполне инициализировать один раз при создаии холдера

2019-06-30 16:58 UTC, jushlwest commented on app/src/main/java/by/itacademy/pvt/homework/dz6/DZ6Singleton.kt
> +    companion object {
обычно этот блок пишут в самом верху файла

2019-06-30 16:58 UTC, jushlwest commented on app/src/main/java/by/itacademy/pvt/homework/dz6/DZ6StudentDetailsActivity.kt
> +        val id = intent.getLongExtra("ID", 0)
ID необходимо в константу вынести

2019-06-30 16:58 UTC, jushlwest commented on app/src/main/java/by/itacademy/pvt/homework/dz6/DZ6StudentDetailsActivity.kt
> +        student = studentSinglton.getStudent(id)
а если не найдете нужного студента, будет креш?

2019-06-30 16:58 UTC, jushlwest commented on app/src/main/java/by/itacademy/pvt/homework/dz6/DZ6StudentDetailsActivity.kt
> +        ImageLoader().load(imageViewDetailDZ6, student.url)
Вообще не понял зачем делать заполнение каждый раз в onResume()? делайте в onCreate()

2019-06-30 16:58 UTC, jushlwest commented on app/src/main/java/by/itacademy/pvt/homework/dz6/DZ6StudentEditActivity.kt
> +        if (id > 2) {
это что за магическая проверка? Я так понимаю разделяете так новго создать или редактировать? выже можете просто проверить если id пришел то редактирование если нет то добавление

2019-06-30 16:58 UTC, jushlwest commented on app/src/main/java/by/itacademy/pvt/homework/dz6/DZ6StudentListActivity.kt
> +        recyclerViewDZ6.adapter = DZ6Adapter(DZ6Singleton.instance.getStudentsList(), this)
адаптер можно один раз создавать но заполнять в onResume()

2019-06-30 17:11 UTC, dmitryf8 commented on app/src/main/java/by/itacademy/pvt/homework/ImageLoader.kt
> +class ImageLoader {
но он может понадобится в других дз, я смогу его использовать, чтобы повторно не писать код заново

2019-06-30 17:12 UTC, dmitryf8 commented on app/src/main/java/by/itacademy/pvt/homework/dz5/CustomDiagramView.kt
> +class CustomDiagramView : View {
случайно закоммитил

2019-06-30 17:19 UTC, dmitryf8 commented on app/src/main/java/by/itacademy/pvt/homework/dz6/DZ6StudentDetailsActivity.kt
> +        val id = intent.getLongExtra("ID", 0)
немного не понимаю. Чтобы получить id, мне нужно получить intent. я могу получить его в onCreate.  Как это реализовать?

2019-06-30 17:24 UTC, dmitryf8 commented on app/src/main/java/by/itacademy/pvt/homework/dz6/DZ6StudentDetailsActivity.kt
> +        student = studentSinglton.getStudent(id)
если не найду, то да. Но эта activity запускается только после клика по item , тоесть id передается существующего студента.

2019-06-30 17:25 UTC, dmitryf8 commented on app/src/main/java/by/itacademy/pvt/homework/dz6/DZ6StudentDetailsActivity.kt
> +        ImageLoader().load(imageViewDetailDZ6, student.url)
для того чтобы обновлялось после возврата из EditStudentActivity

2019-06-30 17:32 UTC, dmitryf8 commented on app/src/main/java/by/itacademy/pvt/homework/dz6/DZ6StudentEditActivity.kt
> +        if (id > 2) {
я не нашел как проверить интент на содержание. Если его нет, то по дефолту id равно 0. Просто из создания нового я отправляю id=1, ну это тестировал передачу Long- параметра

2019-06-30 17:49 UTC, dmitryf8 commented on app/src/main/java/by/itacademy/pvt/homework/dz6/DZ6StudentListActivity.kt
> +        recyclerViewDZ6.adapter = DZ6Adapter(DZ6Singleton.instance.getStudentsList(), this)
а есть такой метод в recyclerView, который передает список? попробовал invalidate(), крэшится, мол нету такого элемента после удаления студента. или в адаптере написать метод, который перезаписывает список? но там ведь происходит бинд по одному элементу в зависимости от позиции

2019-06-30 17:52 UTC, dmitryf8 commented on app/src/main/java/by/itacademy/pvt/homework/dz6/DZ6ListViewHolder.kt
> +        var imageLoader = ImageLoader()
ok

2019-06-30 17:52 UTC, dmitryf8 commented on app/src/main/java/by/itacademy/pvt/homework/dz6/DZ6Singleton.kt
> +    companion object {
ок

2019-06-30 19:36 UTC, eugenia-shumeiko commented on app/src/main/java/by/itacademy/pvt/homework/ImageLoader.kt
> +class ImageLoader {
Речь о том, что не нужен именно как класс. Достаточно в файле этих самых методов, их потом просто по названию вызываешь из любого места программы.

2019-06-30 19:40 UTC, eugenia-shumeiko commented on app/src/main/java/by/itacademy/pvt/homework/dz6/DZ6Adapter.kt
> +        fun onItemClickListener(item: Student)
Для этой функции лучше сделать название что-то вроде "onItemClicked", без "Listener"

2019-06-30 19:43 UTC, dmitryf8 commented on app/src/main/java/by/itacademy/pvt/homework/ImageLoader.kt
> +class ImageLoader {
а, ясно)

2019-06-30 19:43 UTC, eugenia-shumeiko commented on app/src/main/java/by/itacademy/pvt/homework/dz6/DZ6Singleton.kt
> +    fun getIDofStudent(student: Student): Long {
А зачем такая функция? Разве там, где ты ее используешь, нельзя сразу использовать student.id?

2019-06-30 19:50 UTC, dmitryf8 commented on app/src/main/java/by/itacademy/pvt/homework/dz6/DZ6Singleton.kt
> +    fun getIDofStudent(student: Student): Long {
я ее в принципе нигде и не использую, написал на автомате

2019-06-30 19:52 UTC, dmitryf8 commented on app/src/main/java/by/itacademy/pvt/homework/dz6/DZ6Singleton.kt
> +    fun getIDofStudent(student: Student): Long {
удалил

2019-06-30 19:55 UTC, eugenia-shumeiko commented on app/src/main/java/by/itacademy/pvt/homework/dz6/DZ6StudentDetailsActivity.kt
> +        val id = intent.getLongExtra("ID", 0)
Имеется в виду "ID" как ключ в getLongExtra не должно тут быть прописано обычной строкой, должно быть константой

2019-06-30 20:01 UTC, eugenia-shumeiko commented on app/src/main/java/by/itacademy/pvt/homework/dz6/DZ6StudentDetailsActivity.kt
> +            intent.putExtra("ID", student.id)
Вот тут опять - в качестве ключа лучше использовать ту же константу

2019-06-30 20:04 UTC, eugenia-shumeiko commented on app/src/main/java/by/itacademy/pvt/homework/dz6/DZ6StudentDetailsActivity.kt
> +        ImageLoader().load(imageViewDetailDZ6, student.url)
По заданию из EditStudentActivity мы должны попадать не на Dz6StudentDetailsActivity, а на Dz6StudentListActivity.

2019-06-30 20:06 UTC, eugenia-shumeiko commented on app/src/main/java/by/itacademy/pvt/homework/dz6/DZ6StudentEditActivity.kt
> +        val studentSinglton = DZ6Singleton.instance
А зачем сохранять это в переменную? На то он и синглтон, чтобы к нему обращаться сразу через Singletone.instance

2019-06-30 20:12 UTC, eugenia-shumeiko commented on app/src/main/java/by/itacademy/pvt/homework/dz6/DZ6StudentEditActivity.kt
> +                        studentSinglton.getStudent(id),
Зачем это вытягивание студента, а затем его передача туда же? Почему бы в метод edit не передавать сразу id студента, а там уже его искать-изменять?

2019-06-30 20:14 UTC, eugenia-shumeiko commented on app/src/main/java/by/itacademy/pvt/homework/dz6/DZ6StudentEditActivity.kt
> +                    if (nameEditTextDZ6.text.length <= 1) Toast.makeText(this, "Please, enter correct name ", Toast.LENGTH_SHORT).show()
У строки есть очень удобный метод isEmpty(), возможно, с ним будет удобнее.

2019-06-30 20:18 UTC, eugenia-shumeiko commented on app/src/main/java/by/itacademy/pvt/homework/dz6/DZ6StudentEditActivity.kt
> +            saveButtonDZ6.setOnClickListener {
Одной кнопке дважды вешается clickListener и повторно пишется тот же самый код?

2019-07-01 04:51 UTC, dmitryf8 commented on app/src/main/java/by/itacademy/pvt/homework/dz6/DZ6StudentDetailsActivity.kt
> +        val id = intent.getLongExtra("ID", 0)
спасибо, понял, исправил

2019-07-01 04:54 UTC, dmitryf8 commented on app/src/main/java/by/itacademy/pvt/homework/dz6/DZ6StudentEditActivity.kt
> +        if (id > 2) {
нашел, исправил

2019-07-01 04:55 UTC, dmitryf8 commented on app/src/main/java/by/itacademy/pvt/homework/dz6/DZ6StudentListActivity.kt
> +        recyclerViewDZ6.adapter = DZ6Adapter(DZ6Singleton.instance.getStudentsList(), this)
исправил

2019-07-01 04:56 UTC, dmitryf8 commented on app/src/main/java/by/itacademy/pvt/homework/dz6/DZ6Adapter.kt
> +        fun onItemClickListener(item: Student)
ok

2019-07-01 05:03 UTC, dmitryf8 commented on app/src/main/java/by/itacademy/pvt/homework/dz6/DZ6StudentEditActivity.kt
> +            saveButtonDZ6.setOnClickListener {
не совсем тот же, кнопка Save  в зависимости от вызывающей активити либо добавляет нового студента, либо редактирует существующего, поэтому и листенеры вешаются разные

2019-07-01 05:05 UTC, dmitryf8 commented on app/src/main/java/by/itacademy/pvt/homework/dz6/DZ6StudentEditActivity.kt
> +                        studentSinglton.getStudent(id),
можно и так. а в чем разница?

2019-07-01 06:57 UTC, eugenia-shumeiko commented on app/src/main/java/by/itacademy/pvt/homework/dz6/DZ6StudentEditActivity.kt
> +                        studentSinglton.getStudent(id),
Мне это кажется нелогичным и неудобным) Между активити, например, передаётся именно id, здесь по тому же принципу можно. А так только двойная работа, я так считаю...

2019-07-01 07:02 UTC, eugenia-shumeiko commented on app/src/main/java/by/itacademy/pvt/homework/dz6/DZ6StudentEditActivity.kt
> +            saveButtonDZ6.setOnClickListener {
Разница только в edit или add. Так почему бы проверку на наличие id не сделать прямо перед этой операцией? А то повторяются проверки всех полей - двойная работа. Ну и не стоит всё же, я так думаю, на одну кнопку два раза вешать лиснер, это как минимум нелогично.

2019-07-01 07:04 UTC, eugenia-shumeiko commented on app/src/main/java/by/itacademy/pvt/homework/dz6/DZ6StudentEditActivity.kt
> +                    if (!ImageLoader().isURL(urlEditTextDZ6.text.toString())) Toast.makeText(this, "Please, enter correct image URL ", Toast.LENGTH_SHORT).show()
Текст, который выводится в тостах, лучше вынести в strings

2019-07-01 07:13 UTC, eugenia-shumeiko commented on app/src/main/java/by/itacademy/pvt/homework/dz6/DZ6StudentListActivity.kt
> +class DZ6StudentListActivity : Activity(), DZ6Adapter.ClickListener {
У нас в дз еще есть пункт насчет editText, поиска и TextWatcher. И где?)

2019-07-01 07:17 UTC, dmitryf8 commented on app/src/main/java/by/itacademy/pvt/homework/dz6/DZ6StudentListActivity.kt
> +class DZ6StudentListActivity : Activity(), DZ6Adapter.ClickListener {
Что-то я этого не видел, добавили наверное.

2019-07-01 13:42 UTC, tim-teacher requested changes
Пофиксите комменты которые вам оставили

2019-07-01 13:42 UTC, jushlwest commented on app/src/main/java/by/itacademy/pvt/homework/dz6/DZ6Singleton.kt
> +class DZ6Singleton private constructor() {
поменяйте classs на object и это уже будет синглтоном :)

2019-07-01 13:42 UTC, jushlwest commented on app/src/main/java/by/itacademy/pvt/homework/dz6/DZ6StudentDetailsActivity.kt
> +        student = studentSinglton.getStudent(id)
ну и что, а в вдруг там будет засунут не правильный id? кто знает какой разработчки будет писать код который будет дергать вашу активити или с сервера прилетит что то не то

2019-07-01 13:42 UTC, jushlwest commented on app/src/main/java/by/itacademy/pvt/homework/dz6/DZ6StudentDetailsActivity.kt
> +            intent.putExtra("ID", student.id)
Ага

2019-07-01 13:42 UTC, jushlwest commented on app/src/main/java/by/itacademy/pvt/homework/dz6/DZ6StudentEditActivity.kt
> +        val studentSinglton = DZ6Singleton.instance
если для сокращения что бы образаться через более короткую переменную то это нормально

2019-07-01 13:42 UTC, jushlwest commented on app/src/main/java/by/itacademy/pvt/homework/dz6/DZ6StudentEditActivity.kt
> +                        studentSinglton.getStudent(id),
туда нужно весь объект передавать :) иначе если нужно добавить новое поле придется менять сигнатуру метода

2019-07-01 14:08 UTC, eugenia-shumeiko commented on app/src/main/java/by/itacademy/pvt/homework/dz6/DZ6StudentEditActivity.kt
> +                        studentSinglton.getStudent(id),
Надо создавать нового студента с измененными значениями, а в метод уже отдавать его, где класть по нужной позиции? Это имеется в виду или как?

2019-07-01 19:55 UTC, dmitryf8 commented on app/src/main/java/by/itacademy/pvt/homework/dz6/DZ6StudentEditActivity.kt
> +                    if (nameEditTextDZ6.text.length <= 1) Toast.makeText(this, "Please, enter correct name ", Toast.LENGTH_SHORT).show()
я предполагаю, что имя должно состоять более чем из одной буквы

2019-07-01 20:11 UTC, eugenia-shumeiko commented on app/src/main/java/by/itacademy/pvt/homework/dz6/DZ6StudentEditActivity.kt
> +                    if (nameEditTextDZ6.text.length <= 1) Toast.makeText(this, "Please, enter correct name ", Toast.LENGTH_SHORT).show()
Хорошо, допустим (хотя что за дискриминация?!=) Иностранные имена вообще любят сокращать до одной буквы - J, например, и я уж не говорю об азиатских именах!). А что насчет следующей строки с возрастом?)

2019-07-02 19:18 UTC, dmitryf8 commented on app/src/main/java/by/itacademy/pvt/homework/dz6/DZ6StudentEditActivity.kt
> +            saveButtonDZ6.setOnClickListener {
Проверку на наличие ID я сделал в начале. Далее в зависимости от этого результата присваивается листенер (edit или add), который проверяет правильность заполнения ВСЕХ полей, и если всё ок, то выполняется действие, если нет, то повторной проверкой выясняю, какое именно поле заполнено неправильно. Как можно улучшить?

2019-07-02 19:39 UTC, eugenia-shumeiko commented on app/src/main/java/by/itacademy/pvt/homework/dz6/DZ6StudentEditActivity.kt
> +            saveButtonDZ6.setOnClickListener {
По идее, проверку на hasExtra можно вообще убрать, т.к. getLongExtra возвращает null, если нет Extra. И дальше нужна проверка именно id (точнее, даже студента с таким id) - null или нет, а это можно делать внутри clickListener, и в зависимости от результата подставлять после проверки всех полей edit или add.

2019-07-02 19:42 UTC, eugenia-shumeiko commented on app/src/main/java/by/itacademy/pvt/homework/dz6/Student.kt
> +    var url = url
Как нам сказали, поля студента должны быть неизменяемыми, а id должна генериться не тут (чтобы при update создавать нового Студента с новыми полями, но старым id)

2019-07-02 19:45 UTC, dmitryf8 commented on app/src/main/java/by/itacademy/pvt/homework/dz6/Student.kt
> +    var url = url
тоесть id нам нужно явно задавать при создании?

2019-07-02 19:48 UTC, eugenia-shumeiko commented on app/src/main/java/by/itacademy/pvt/homework/dz6/Student.kt
> +    var url = url
Ага

2019-07-03 13:17 UTC, eugenia-shumeiko commented on app/src/main/java/by/itacademy/pvt/homework/dz6/DZ6Adapter.kt
> +        items = DZ6Singleton.instance.getStudentsList()
Адаптер не должен напрямую обращаться к синглтону. Метод updateList должен принимать на вход новый список и применять его

2019-07-03 20:26 UTC, dmitryf8 commented on app/src/main/java/by/itacademy/pvt/homework/dz6/DZ6Adapter.kt
> +        items = DZ6Singleton.instance.getStudentsList()
ok

2019-07-05 12:18 UTC, jushlwest commented on app/src/main/java/by/itacademy/pvt/homework/dz6/DZ6StudentEditActivity.kt
> +                        studentSinglton.getStudent(id),
да

2019-07-05 12:25 UTC, tim-teacher approved these changes
Пофиксите только то что в комментах вам написали

2019-07-05 12:25 UTC, jushlwest commented on app/src/main/java/by/itacademy/pvt/homework/dz6/DZ6Singleton.kt
> +        studentList.add(student)
студент добавится в конец списка соответвенно на листе будет отображаться в другой позиции, нужно менять в той же позиции где и был предыдущий

2019-07-05 12:25 UTC, jushlwest commented on app/src/main/java/by/itacademy/pvt/homework/dz6/DZ6StudentEditActivity.kt
> +            saveButtonDZ6.setOnClickListener {
да логика странная с кликами, сделайте как вам выше советовали

2019-07-05 12:25 UTC, jushlwest commented on app/src/main/java/by/itacademy/pvt/homework/dz6/DZ6StudentListActivity.kt
> +                (recyclerViewDZ6.adapter as DZ6Adapter).showList(
зачем это привидение если вы чуть выше сами создавали этот адаптер?

2019-07-05 20:09 UTC, merged